language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
services:
  - mongodb
  - redis-server
  - memcached
cache: pip
install:
- pip install setuptools --upgrade; pip install -r test_requirements.txt; python setup.py
  install
script:
  - nosetests --with-coverage --cover-package=flask_session --with-timer
after_success: coveralls
